spring.application.name=vehiclesMaintenance

springdoc.api-docs.enabled=true
springdoc.api-docs.path=/vehicles-maintenance/v3/api-docs

springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/vehicles-maintenance/swagger-ui.html

spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5433/maintenance_db
spring.datasource.username=lucas.bx
spring.datasource.password=123321ABC
spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.org.springframework.security=DEBUG